### ISSUE TITLE
test.py fails with NameError

### ISSUE THREAD

**Issue by abhikpal** [jonay2000/p5.py#3]
When run, test.py produces a blank window and the following traceback when the window is closed:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from p5 import *
  File "/home/abhikpal/p5.py/p5/__init__.py", line 60, in <module>
    init = Init()
  File "/home/abhikpal/p5.py/p5/__init__.py", line 30, in __init__
    self.start()
  File "/home/abhikpal/p5.py/p5/__init__.py", line 57, in start
    window.window.dispatch_events()

    ...
    
  File "/home/abhikpal/p5.py/p5/classes.py", line 17, in on_close
    Globals.WINDOWMANAGER.remove(self)
  File "/home/abhikpal/p5.py/p5/core.py", line 21, in remove
    Globals.RUNNING = False
NameError: name 'Globals' is not defined
```

**Comment by jdonszelmann** [comment]
yeah, just fixed that :)! global variables weren't importing correctly and it kept running the window even though it closed. thanks though.
