### ISSUE TITLE
test.py fails when mouse is inside the window

### ISSUE THREAD

**Issue by abhikpal** [jonay2000/p5.py#4]
```python
test.py
No keyPressed
No keyReleased
No keyTyped
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from p5 import *
  File ".../p5.py/p5/__init__.py", line 81, in <module>
    init = Init()
  File ".../p5.py/p5/__init__.py", line 50, in __init__
    self.start()
  File ".../p5.py/p5/__init__.py", line 70, in start
    event_loop.run()
  File ".../lib/python3.6/site-packages/pyglet/app/base.py", line 136, in run
    self._run_estimated()
  File ".../lib/python3.6/site-packages/pyglet/app/base.py", line 175, in _run_estimated
    if not platform_event_loop.step(estimate) and estimate != 0.0 and \
  File ".../lib/python3.6/site-packages/pyglet/app/xlib.py", line 124, in step
    device.select()
  File ".../lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 165, in select
    dispatch(e)
  File ".../lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 900, in dispatch_platform_event_view
    event_handler(e)
  File ".../lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 1242, in _event_enternotify
    y = self._mouse_y = self.height - ev.xcrossing.y
TypeError: unsupported operand type(s) for -: 'method' and 'int'
```

**Comment by jonay2000** [comment]
wtf....

**Comment by jdonszelmann** [comment]
could you retry it now (its updated and for me it works fine on mac/windows). have not yet tested linux but should work. if you want to install it just use pip install p5.py - its up there

**Comment by abhikpal** [comment]
Nope. Still not working. Getting a different error, though:

```python
test.py
No keyReleased
No keyTyped
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from p5 import *
  File ".../p5.py/p5/__init__.py", line 81, in <module>
    init = Init()
  File ".../p5.py/p5/__init__.py", line 50, in __init__
    self.start()
  File ".../p5.py/p5/__init__.py", line 54, in start
    self.setup()
  File "test.py", line 9, in setup
    print(pymap(5,0,10,0,1))
TypeError: 'int' object is not iterable
```

**Comment by jdonszelmann** [comment]
ye i know that one - just a test. we found the error and it has to do with the way we figure out how objects that do not need to update stay on the screen (for some extra speed). a fix is coming.

**Comment by jdonszelmann** [comment]
by the way - we got snake working! its on github.
